ohos: fix build with llvm/clang 22 about missing initializer
src/plugins/ohos/qohoswebviewcontroller.cpp:258:21: error: missing field 'jsComponentContent' initializer [-Werror,-Wmissing-designated-field-initializers]
  258 |                     }));
      |                     ^

Pick-to: 6.12
Change-Id: I7c09a23df32edc4282ac03c6ca14bf6fe14f23e3
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>